from . import (
    base,
    role_policy_menu_action_common,
    ir_actions,
    ir_http,
    ir_model_access,
    ir_ui_menu,
    ir_ui_view,
    model_method_execution_right,
    res_groups,
    res_role,
    res_role_acl,
    res_users,
    security_policy_tag,
    view_model_operation,
    view_modifier_rule,
    view_type_attribute,
)
